sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t wrtv23/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true wrtv23/react-test npm run test -- --coverage

after_success:
  - docker build -t wrtv23/fibonacci-client ./client
  - docker build -t wrtv23/fibonacci-nginx ./nginx
  - docker build -t wrtv23/fibonacci-server ./server
  - docker build -t wrtv23/fibonacci-worker ./worker
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  - docker push wrtv23/fibonacci-client
  - docker push wrtv23/fibonacci-nginx
  - docker push wrtv23/fibonacci-server
  - docker push wrtv23/fibonacci-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "fibonacci_app"
  env: "FibonacciApp-env"
  bucket_name: "elasticbeanstalk-us-east-1-358967056985"
  bucket_path: "fibonacci_app"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  on:
    branch: master
